# Add your configuration here (paths, DB creds via env vars, features)
# Example:
# data_source:
#   mysql:
#     host: ${MYSQL_HOST}
#     port: ${MYSQL_PORT}
#     user: ${MYSQL_USER}
#     password: ${MYSQL_PASSWORD}
#     database: ${MYSQL_DATABASE}

data:
  mysql_table: house_prices
  raw_path: artifacts/raw_data/data.csv
  sale_path: artifacts/raw_data/sale.csv
  rent_path: artifacts/raw_data/rent.csv

transformed:
  sale_dir: artifacts/transformed_data/sale/
  rent_dir: artifacts/transformed_data/rent/